# 04 — Portfolio and Risk Demo

This notebook demonstrates how exported signals map to portfolio-level benchmark metrics.

In [7]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display, Markdown

ROOT = Path.cwd().resolve().parent if Path.cwd().name == 'notebooks' else Path.cwd().resolve()
PROCESSED = ROOT / 'data' / 'processed'

pf_path = PROCESSED / 'portfolio_backtest_summary.csv'
snapshot_path = PROCESSED / 'signals_latest_snapshot.csv'
ml_pf_path = PROCESSED / 'ml_backtest_summary.csv'
ml_stability_path = PROCESSED / 'ml_backtest_stability.csv'
regime_summary_path = PROCESSED / 'regime_backtest_summary.csv'
router_path = PROCESSED / 'regime_router_decisions.csv'
unified_path = PROCESSED / 'unified_backtest_summary.csv'
unified_inf_path = PROCESSED / 'unified_backtest_inference.csv'

missing = [p for p in [pf_path, snapshot_path, ml_pf_path, ml_stability_path, regime_summary_path, router_path, unified_path, unified_inf_path] if not p.exists()]
print(f'Missing artifacts: {len(missing)}')
for p in missing:
    print(' -', p)

Missing artifacts: 0

## Evidence Governance for Portfolio Claims

### Claim Policy
- **Supported by statistical evidence**: effect remains after inference and robustness checks.
- **Economically promising but not statistically strong**: attractive metrics with weak significance.
- **Exploratory / not used for headline claims**: stress or diagnostic views only.

Interpret portfolio outcomes with uncertainty and cost drag first, then practical implications.

In [8]:
pf = pd.read_csv(pf_path) if pf_path.exists() else pd.DataFrame()
snapshot = pd.read_csv(snapshot_path) if snapshot_path.exists() else pd.DataFrame()
ml_pf = pd.read_csv(ml_pf_path) if ml_pf_path.exists() else pd.DataFrame()
ml_stability = pd.read_csv(ml_stability_path) if ml_stability_path.exists() else pd.DataFrame()
regime_summary = pd.read_csv(regime_summary_path) if regime_summary_path.exists() else pd.DataFrame()
router = pd.read_csv(router_path) if router_path.exists() else pd.DataFrame()
unified = pd.read_csv(unified_path) if unified_path.exists() else pd.DataFrame()
unified_inf = pd.read_csv(unified_inf_path) if unified_inf_path.exists() else pd.DataFrame()

display(Markdown('## Portfolio Backtest Summary (Classical)'))
display(pf)

display(Markdown('## Portfolio Backtest Summary (ML)'))
display(ml_pf)

display(Markdown('## ML Stability (cost/threshold stress test)'))
display(ml_stability)

display(Markdown('## Unified Strategy Performance (headline comparison)'))
display(unified)

display(Markdown('## Regime Strategy Performance (operator view)'))
display(regime_summary)

display(Markdown('## Router Decisions (confidence + expected edge)'))
display(router)

display(Markdown('## Unified Inference (bootstrap + paired test)'))
display(unified_inf)

display(Markdown('## Latest Signal Snapshot Used by Strategy Layer'))
display(snapshot)

## Portfolio Backtest Summary (Classical)

,strategy,ann_return,ann_vol,ann_sharpe,ann_sortino,calmar,cagr,total_return,max_drawdown,var95_empirical,var95_parametric,mean_return,hit_ratio,active_pct,ann_turnover,avg_turnover,total_cost_drag,benchmark,excess_ann_return_vs_benchmark,sharpe_delta_vs_benchmark
0,strategy,-0.004029,0.012861,-0.3133,-0.3306,-0.0678,-0.004104,-0.032362,-0.0605,0.0061,0.0061,-0.000336,0.4583,0.7083,0.4391,0.036589,0.001756,naive_50_50,-0.000883,-0.0226
1,naive_50_50,-0.003146,0.010823,-0.2907,-0.3207,-0.0614,-0.003199,-0.025309,-0.0521,0.0053,0.0051,-0.000262,0.4479,1.0000,0.0000,0.000000,0.000000,naive_50_50,0.000000,0.0000
2,disconnected_60_40,-0.004292,0.012794,-0.3354,-0.3721,-0.0690,-0.004364,-0.034385,-0.0633,0.0063,0.0061,-0.000358,0.4375,1.0000,0.0000,0.000000,0.000000,naive_50_50,-0.001146,-0.0447

## Portfolio Backtest Summary (ML)

,strategy,ann_return,ann_vol,ann_sharpe,ann_sortino,calmar,cagr,total_return,max_drawdown,var95_empirical,var95_parametric,mean_return,hit_ratio,active_pct,ann_turnover,avg_turnover,total_cost_drag,benchmark,excess_ann_return_vs_benchmark,sharpe_delta_vs_benchmark
0,ml_strategy,0.002514,0.017185,0.1463,0.1597,0.0671,0.002373,0.006938,-0.0353,0.0093,0.0082,0.000210,0.2857,0.5143,4.8000,0.400000,0.0070,ml_passive_spread,0.019487,0.9568
1,ml_passive_spread,-0.016973,0.020940,-0.8105,-1.1588,-0.2530,-0.017051,-0.048925,-0.0674,0.0114,0.0099,-0.001414,0.3429,1.0000,0.3429,0.028571,0.0005,ml_passive_spread,0.000000,0.0000

## ML Stability (cost/threshold stress test)

   prob_long  prob_short  cost_bps  active_pct  ann_sharpe  ann_return
0       0.55        0.45       5.0    0.742857    0.013906    0.000252
1       0.60        0.40       5.0    0.600000   -0.290805   -0.004992
2       0.55        0.45      10.0    0.742857   -0.089060   -0.001634

## Unified Strategy Performance (headline comparison)

,strategy,ann_return,ann_vol,ann_sharpe,ann_sortino,calmar,cagr,total_return,max_drawdown,var95_empirical,...,ann_turnover,avg_turnover,total_cost_drag,benchmark,excess_ann_return_vs_benchmark,sharpe_delta_vs_benchmark,family,regime_id,regime_cell,n_obs
0,strategy,-0.004029,0.012861,-0.3133,-0.3306,-0.0678,-0.004104,-0.032362,-0.0605,0.0061,...,0.4391,0.036589,0.001756,naive_50_50,-0.000883,-0.0226,classical,NaN,NaN,NaN
1,naive_50_50,-0.003146,0.010823,-0.2907,-0.3207,-0.0614,-0.003199,-0.025309,-0.0521,0.0053,...,0.0000,0.000000,0.000000,naive_50_50,0.000000,0.0000,classical,NaN,NaN,NaN
2,disconnected_60_40,-0.004292,0.012794,-0.3354,-0.3721,-0.0690,-0.004364,-0.034385,-0.0633,0.0063,...,0.0000,0.000000,0.000000,naive_50_50,-0.001146,-0.0447,classical,NaN,NaN,NaN
3,ml_strategy,0.002514,0.017185,0.1463,0.1597,0.0671,0.002373,0.006938,-0.0353,0.0093,...,4.8000,0.400000,0.007000,ml_passive_spread,0.019487,0.9568,ml,NaN,NaN,NaN
4,ml_passive_spread,-0.016973,0.020940,-0.8105,-1.1588,-0.2530,-0.017051,-0.048925,-0.0674,0.0114,...,0.3429,0.028571,0.000500,ml_passive_spread,0.000000,0.0000,ml,NaN,NaN,NaN
5,CL_PANEL,-0.005523,0.010254,-0.5386,-0.5269,-0.1789,-0.005560,-0.026590,-0.0311,0.0051,...,1.3190,0.109914,0.003188,PASSIVE_SPREAD,0.011015,0.1204,regime_router,regime_R1,R1_high_spread,58.0
6,CL_SPREAD,-0.005523,0.010254,-0.5386,-0.5269,-0.1789,-0.005560,-0.026590,-0.0311,0.0051,...,1.3190,0.109914,0.003188,PASSIVE_SPREAD,0.011015,0.1204,regime_router,regime_R1,R1_high_spread,58.0
7,ML_ENS,0.002514,0.017185,0.1463,0.1597,0.0671,0.002373,0.006938,-0.0353,0.0093,...,4.8000,0.400000,0.007000,PASSIVE_SPREAD,0.019487,0.9568,regime_router,regime_R1,R1_high_spread,58.0
8,ML_LOGIT,-0.015913,0.019864,-0.8011,-1.0620,-0.2696,-0.015987,-0.045917,-0.0593,0.0113,...,6.5143,0.542857,0.009500,PASSIVE_SPREAD,0.001060,0.0094,regime_router,regime_R1,R1_high_spread,58.0
9,ML_RF,-0.004160,0.019310,-0.2154,-0.2885,-0.0862,-0.004333,-0.012585,-0.0503,0.0093,...,6.5143,0.542857,0.009500,PASSIVE_SPREAD,0.012813,0.5951,regime_router,regime_R1,R1_high_spread,58.0
10,CL_PANEL,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_router,regime_R1,other,24.0
11,CL_SPREAD,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_router,regime_R1,other,24.0
12,CL_PANEL,0.002179,0.003444,0.6327,0.8089,0.8706,0.002176,0.002539,-0.0025,0.0011,...,1.5714,0.130952,0.000917,PASSIVE_SPREAD,0.014401,1.7887,regime_router,regime_R1,R1_low_spread,14.0
13,CL_SPREAD,0.002179,0.003444,0.6327,0.8089,0.8706,0.002176,0.002539,-0.0025,0.0011,...,1.5714,0.130952,0.000917,PASSIVE_SPREAD,0.014401,1.7887,regime_router,regime_R1,R1_low_spread,14.0
14,CL_PANEL,-0.000234,0.008495,-0.0276,-0.0315,-0.0113,-0.000270,-0.001056,-0.0238,0.0041,...,1.4362,0.119681,0.002812,PASSIVE_SPREAD,0.014887,0.5273,regime_router,regime_M1,M1_high_rates,47.0
15,CL_SPREAD,-0.000234,0.008495,-0.0276,-0.0315,-0.0113,-0.000270,-0.001056,-0.0238,0.0041,...,1.4362,0.119681,0.002812,PASSIVE_SPREAD,0.014887,0.5273,regime_router,regime_M1,M1_high_rates,47.0
16,ML_ENS,0.002514,0.017185,0.1463,0.1597,0.0671,0.002373,0.006938,-0.0353,0.0093,...,4.8000,0.400000,0.007000,PASSIVE_SPREAD,0.019487,0.9568,regime_router,regime_M1,M1_high_rates,47.0
17,ML_LOGIT,-0.015913,0.019864,-0.8011,-1.0620,-0.2696,-0.015987,-0.045917,-0.0593,0.0113,...,6.5143,0.542857,0.009500,PASSIVE_SPREAD,0.001060,0.0094,regime_router,regime_M1,M1_high_rates,47.0
18,ML_RF,-0.004160,0.019310,-0.2154,-0.2885,-0.0862,-0.004333,-0.012585,-0.0503,0.0093,...,6.5143,0.542857,0.009500,PASSIVE_SPREAD,0.012813,0.5951,regime_router,regime_M1,M1_high_rates,47.0
19,CL_PANEL,-0.004602,0.005025,-0.9157,-0.8860,-0.3751,-0.004604,-0.009568,-0.0123,0.0030,...,1.4600,0.121667,0.001521,PASSIVE_SPREAD,0.012183,0.4460,regime_router,regime_M1,M1_low_rates,25.0
20,CL_SPREAD,-0.004602,0.005025,-0.9157,-0.8860,-0.3751,-0.004604,-0.009568,-0.0123,0.0030,...,1.4600,0.121667,0.001521,PASSIVE_SPREAD,0.012183,0.4460,regime_router,regime_M1,M1_low_rates,25.0
21,CL_PANEL,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_router,regime_M1,other,24.0
22,CL_SPREAD,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_router,regime_M1,other,24.0
23,CL_PANEL,-0.003570,0.008035,-0.4443,-0.4683,-0.1425,-0.003596,-0.012232,-0.0252,0.0042,...,1.6220,0.135163,0.002771,PASSIVE_SPREAD,0.010081,0.1664,regime_router,regime_C1,C1_macro_tight_calm,41.0
24,CL_SPREAD,-0.003570,0.008035,-0.4443,-0.4683,-0.1425,-0.003596,-0.012232,-0.0252,0.0042,...,1.6220,0.135163,0.002771,PASSIVE_SPREAD,0.010081,0.1664,regime_router,regime_C1,C1_macro_tight_calm,41.0
25,ML_ENS,0.000694,0.018021,0.0385,0.0441,0.0152,0.000537,0.001387,-0.0353,0.0101,...,5.4194,0.451613,0.007000,PASSIVE_SPREAD,0.021651,1.0198,regime_router,regime_C1,C1_macro_tight_calm,41.0
26,ML_LOGIT,-0.015486,0.018956,-0.8169,-1.0516,-0.2986,-0.015548,-0.039673,-0.0521,0.0110,...,5.0323,0.419355,0.006500,PASSIVE_SPREAD,0.005471,0.1644,regime_router,regime_C1,C1_macro_tight_calm,41.0
27,ML_RF,-0.009232,0.019218,-0.4804,-0.5734,-0.1499,-0.009371,-0.024028,-0.0625,0.0115,...,5.0323,0.419355,0.006500,PASSIVE_SPREAD,0.011725,0.5009,regime_router,regime_C1,C1_macro_tight_calm,41.0
28,CL_PANEL,-0.004602,0.005025,-0.9157,-0.8860,-0.3751,-0.004604,-0.009568,-0.0123,0.0030,...,1.4600,0.121667,0.001521,PASSIVE_SPREAD,0.012183,0.4460,regime_router,regime_C1,C1_macro_loose,25.0
29,CL_SPREAD,-0.004602,0.005025,-0.9157,-0.8860,-0.3751,-0.004604,-0.009568,-0.0123,0.0030,...,1.4600,0.121667,0.001521,PASSIVE_SPREAD,0.012183,0.4460,regime_router,regime_C1,C1_macro_loose,25.0
30,CL_PANEL,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_router,regime_C1,other,24.0
31,CL_SPREAD,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_router,regime_C1,other,24.0
32,CL_PANEL,-0.004344,0.007919,-0.5485,-0.4451,-0.1576,-0.004366,-0.018424,-0.0277,0.0028,...,1.7255,0.143791,0.003667,PASSIVE_SPREAD,0.019749,0.7394,regime_router,ms_state_persist,MS_low,51.0
33,CL_SPREAD,-0.004344,0.007919,-0.5485,-0.4451,-0.1576,-0.004366,-0.018424,-0.0277,0.0028,...,1.7255,0.143791,0.003667,PASSIVE_SPREAD,0.019749,0.7394,regime_router,ms_state_persist,MS_low,51.0
34,ML_ENS,0.002111,0.003722,0.5671,11.8596,2.3130,0.002107,0.002107,-0.0009,0.0005,...,4.0000,0.333333,0.002000,PASSIVE_SPREAD,0.021620,1.7784,regime_router,ms_state_persist,MS_low,51.0
35,ML_LOGIT,0.009399,0.012510,0.7513,1.0464,0.9450,0.009367,0.009367,-0.0099,0.0049,...,7.0000,0.583333,0.003500,PASSIVE_SPREAD,0.028908,1.9626,regime_router,ms_state_persist,MS_low,51.0
36,ML_RF,-0.007135,0.017729,-0.4024,-0.4523,-0.2924,-0.007255,-0.007255,-0.0248,0.0092,...,5.0000,0.416667,0.002500,PASSIVE_SPREAD,0.012374,0.8089,regime_router,ms_state_persist,MS_low,51.0
37,CL_PANEL,-0.004684,0.008658,-0.5410,-0.5597,-0.1729,-0.004710,-0.017164,-0.0272,0.0060,...,2.1023,0.175189,0.003854,PASSIVE_SPREAD,-0.007338,-0.6585,regime_router,ms_state_persist,MS_high,44.0
38,CL_SPREAD,-0.004684,0.008658,-0.5410,-0.5597,-0.1729,-0.004710,-0.017164,-0.0272,0.0060,...,2.1023,0.175189,0.003854,PASSIVE_SPREAD,-0.007338,-0.6585,regime_router,ms_state_persist,MS_high,44.0
39,ML_ENS,-0.009763,0.020027,-0.4875,-0.5614,-0.2314,-0.009910,-0.018907,-0.0428,0.0116,...,5.2174,0.434783,0.005000,PASSIVE_SPREAD,0.006147,0.1920,regime_router,ms_state_persist,MS_high,44.0
40,ML_LOGIT,-0.032900,0.021202,-1.5517,-2.0601,-0.5214,-0.032617,-0.061581,-0.0626,0.0119,...,6.7826,0.565217,0.006500,PASSIVE_SPREAD,-0.016990,-0.8722,regime_router,ms_state_persist,MS_high,44.0
41,ML_RF,-0.016071,0.020983,-0.7659,-1.0116,-0.3125,-0.016160,-0.030745,-0.0517,0.0116,...,7.8261,0.652174,0.007500,PASSIVE_SPREAD,-0.000161,-0.0864,regime_router,ms_state_persist,MS_high,44.0

## Regime Strategy Performance (operator view)

,strategy,ann_return,ann_vol,ann_sharpe,ann_sortino,calmar,cagr,total_return,max_drawdown,var95_empirical,...,ann_turnover,avg_turnover,total_cost_drag,benchmark,excess_ann_return_vs_benchmark,sharpe_delta_vs_benchmark,regime_id,regime_cell,n_obs,family
0,CL_PANEL,-0.005523,0.010254,-0.5386,-0.5269,-0.1789,-0.005560,-0.026590,-0.0311,0.0051,...,1.3190,0.109914,0.003188,PASSIVE_SPREAD,0.011015,0.1204,regime_R1,R1_high_spread,58,regime_router
1,CL_SPREAD,-0.005523,0.010254,-0.5386,-0.5269,-0.1789,-0.005560,-0.026590,-0.0311,0.0051,...,1.3190,0.109914,0.003188,PASSIVE_SPREAD,0.011015,0.1204,regime_R1,R1_high_spread,58,regime_router
2,ML_ENS,0.002514,0.017185,0.1463,0.1597,0.0671,0.002373,0.006938,-0.0353,0.0093,...,4.8000,0.400000,0.007000,PASSIVE_SPREAD,0.019487,0.9568,regime_R1,R1_high_spread,58,regime_router
3,ML_LOGIT,-0.015913,0.019864,-0.8011,-1.0620,-0.2696,-0.015987,-0.045917,-0.0593,0.0113,...,6.5143,0.542857,0.009500,PASSIVE_SPREAD,0.001060,0.0094,regime_R1,R1_high_spread,58,regime_router
4,ML_RF,-0.004160,0.019310,-0.2154,-0.2885,-0.0862,-0.004333,-0.012585,-0.0503,0.0093,...,6.5143,0.542857,0.009500,PASSIVE_SPREAD,0.012813,0.5951,regime_R1,R1_high_spread,58,regime_router
5,CL_PANEL,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_R1,other,24,regime_router
6,CL_SPREAD,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_R1,other,24,regime_router
7,CL_PANEL,0.002179,0.003444,0.6327,0.8089,0.8706,0.002176,0.002539,-0.0025,0.0011,...,1.5714,0.130952,0.000917,PASSIVE_SPREAD,0.014401,1.7887,regime_R1,R1_low_spread,14,regime_router
8,CL_SPREAD,0.002179,0.003444,0.6327,0.8089,0.8706,0.002176,0.002539,-0.0025,0.0011,...,1.5714,0.130952,0.000917,PASSIVE_SPREAD,0.014401,1.7887,regime_R1,R1_low_spread,14,regime_router
9,CL_PANEL,-0.000234,0.008495,-0.0276,-0.0315,-0.0113,-0.000270,-0.001056,-0.0238,0.0041,...,1.4362,0.119681,0.002812,PASSIVE_SPREAD,0.014887,0.5273,regime_M1,M1_high_rates,47,regime_router
10,CL_SPREAD,-0.000234,0.008495,-0.0276,-0.0315,-0.0113,-0.000270,-0.001056,-0.0238,0.0041,...,1.4362,0.119681,0.002812,PASSIVE_SPREAD,0.014887,0.5273,regime_M1,M1_high_rates,47,regime_router
11,ML_ENS,0.002514,0.017185,0.1463,0.1597,0.0671,0.002373,0.006938,-0.0353,0.0093,...,4.8000,0.400000,0.007000,PASSIVE_SPREAD,0.019487,0.9568,regime_M1,M1_high_rates,47,regime_router
12,ML_LOGIT,-0.015913,0.019864,-0.8011,-1.0620,-0.2696,-0.015987,-0.045917,-0.0593,0.0113,...,6.5143,0.542857,0.009500,PASSIVE_SPREAD,0.001060,0.0094,regime_M1,M1_high_rates,47,regime_router
13,ML_RF,-0.004160,0.019310,-0.2154,-0.2885,-0.0862,-0.004333,-0.012585,-0.0503,0.0093,...,6.5143,0.542857,0.009500,PASSIVE_SPREAD,0.012813,0.5951,regime_M1,M1_high_rates,47,regime_router
14,CL_PANEL,-0.004602,0.005025,-0.9157,-0.8860,-0.3751,-0.004604,-0.009568,-0.0123,0.0030,...,1.4600,0.121667,0.001521,PASSIVE_SPREAD,0.012183,0.4460,regime_M1,M1_low_rates,25,regime_router
15,CL_SPREAD,-0.004602,0.005025,-0.9157,-0.8860,-0.3751,-0.004604,-0.009568,-0.0123,0.0030,...,1.4600,0.121667,0.001521,PASSIVE_SPREAD,0.012183,0.4460,regime_M1,M1_low_rates,25,regime_router
16,CL_PANEL,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_M1,other,24,regime_router
17,CL_SPREAD,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_M1,other,24,regime_router
18,CL_PANEL,-0.003570,0.008035,-0.4443,-0.4683,-0.1425,-0.003596,-0.012232,-0.0252,0.0042,...,1.6220,0.135163,0.002771,PASSIVE_SPREAD,0.010081,0.1664,regime_C1,C1_macro_tight_calm,41,regime_router
19,CL_SPREAD,-0.003570,0.008035,-0.4443,-0.4683,-0.1425,-0.003596,-0.012232,-0.0252,0.0042,...,1.6220,0.135163,0.002771,PASSIVE_SPREAD,0.010081,0.1664,regime_C1,C1_macro_tight_calm,41,regime_router
20,ML_ENS,0.000694,0.018021,0.0385,0.0441,0.0152,0.000537,0.001387,-0.0353,0.0101,...,5.4194,0.451613,0.007000,PASSIVE_SPREAD,0.021651,1.0198,regime_C1,C1_macro_tight_calm,41,regime_router
21,ML_LOGIT,-0.015486,0.018956,-0.8169,-1.0516,-0.2986,-0.015548,-0.039673,-0.0521,0.0110,...,5.0323,0.419355,0.006500,PASSIVE_SPREAD,0.005471,0.1644,regime_C1,C1_macro_tight_calm,41,regime_router
22,ML_RF,-0.009232,0.019218,-0.4804,-0.5734,-0.1499,-0.009371,-0.024028,-0.0625,0.0115,...,5.0323,0.419355,0.006500,PASSIVE_SPREAD,0.011725,0.5009,regime_C1,C1_macro_tight_calm,41,regime_router
23,CL_PANEL,-0.004602,0.005025,-0.9157,-0.8860,-0.3751,-0.004604,-0.009568,-0.0123,0.0030,...,1.4600,0.121667,0.001521,PASSIVE_SPREAD,0.012183,0.4460,regime_C1,C1_macro_loose,25,regime_router
24,CL_SPREAD,-0.004602,0.005025,-0.9157,-0.8860,-0.3751,-0.004604,-0.009568,-0.0123,0.0030,...,1.4600,0.121667,0.001521,PASSIVE_SPREAD,0.012183,0.4460,regime_C1,C1_macro_loose,25,regime_router
25,CL_PANEL,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_C1,other,24,regime_router
26,CL_SPREAD,0.000991,0.001998,0.4957,0.5857,0.5386,0.000989,0.001979,-0.0018,0.0003,...,1.5000,0.125000,0.001500,PASSIVE_SPREAD,0.000479,0.4514,regime_C1,other,24,regime_router
27,CL_PANEL,-0.004344,0.007919,-0.5485,-0.4451,-0.1576,-0.004366,-0.018424,-0.0277,0.0028,...,1.7255,0.143791,0.003667,PASSIVE_SPREAD,0.019749,0.7394,ms_state_persist,MS_low,51,regime_router
28,CL_SPREAD,-0.004344,0.007919,-0.5485,-0.4451,-0.1576,-0.004366,-0.018424,-0.0277,0.0028,...,1.7255,0.143791,0.003667,PASSIVE_SPREAD,0.019749,0.7394,ms_state_persist,MS_low,51,regime_router
29,ML_ENS,0.002111,0.003722,0.5671,11.8596,2.3130,0.002107,0.002107,-0.0009,0.0005,...,4.0000,0.333333,0.002000,PASSIVE_SPREAD,0.021620,1.7784,ms_state_persist,MS_low,51,regime_router
30,ML_LOGIT,0.009399,0.012510,0.7513,1.0464,0.9450,0.009367,0.009367,-0.0099,0.0049,...,7.0000,0.583333,0.003500,PASSIVE_SPREAD,0.028908,1.9626,ms_state_persist,MS_low,51,regime_router
31,ML_RF,-0.007135,0.017729,-0.4024,-0.4523,-0.2924,-0.007255,-0.007255,-0.0248,0.0092,...,5.0000,0.416667,0.002500,PASSIVE_SPREAD,0.012374,0.8089,ms_state_persist,MS_low,51,regime_router
32,CL_PANEL,-0.004684,0.008658,-0.5410,-0.5597,-0.1729,-0.004710,-0.017164,-0.0272,0.0060,...,2.1023,0.175189,0.003854,PASSIVE_SPREAD,-0.007338,-0.6585,ms_state_persist,MS_high,44,regime_router
33,CL_SPREAD,-0.004684,0.008658,-0.5410,-0.5597,-0.1729,-0.004710,-0.017164,-0.0272,0.0060,...,2.1023,0.175189,0.003854,PASSIVE_SPREAD,-0.007338,-0.6585,ms_state_persist,MS_high,44,regime_router
34,ML_ENS,-0.009763,0.020027,-0.4875,-0.5614,-0.2314,-0.009910,-0.018907,-0.0428,0.0116,...,5.2174,0.434783,0.005000,PASSIVE_SPREAD,0.006147,0.1920,ms_state_persist,MS_high,44,regime_router
35,ML_LOGIT,-0.032900,0.021202,-1.5517,-2.0601,-0.5214,-0.032617,-0.061581,-0.0626,0.0119,...,6.7826,0.565217,0.006500,PASSIVE_SPREAD,-0.016990,-0.8722,ms_state_persist,MS_high,44,regime_router
36,ML_RF,-0.016071,0.020983,-0.7659,-1.0116,-0.3125,-0.016160,-0.030745,-0.0517,0.0116,...,7.8261,0.652174,0.007500,PASSIVE_SPREAD,-0.000161,-0.0864,ms_state_persist,MS_high,44,regime_router

## Router Decisions (confidence + expected edge)

,regime_id,regime_cell,selected_model,router_score,selected_ann_sharpe,confidence,expected_net_edge,reason_code,no_trade,n_obs,label_version,router_policy_version
0,regime_R1,R1_high_spread,neutral,-0.131825,0.1463,0.263706,-0.001672,low_confidence_or_edge,1,58,v2_triple_barrier_meta,v2_risk_confidence_weighted
1,regime_R1,other,CL_PANEL,0.314445,0.4957,0.500000,0.003144,score_selected,0,24,v2_triple_barrier_meta,v2_risk_confidence_weighted
2,regime_R1,R1_low_spread,CL_PANEL,0.430853,0.6327,0.500000,0.004309,score_selected,0,14,v2_triple_barrier_meta,v2_risk_confidence_weighted
3,regime_M1,M1_high_rates,neutral,-0.095951,-0.0276,0.263706,-0.001672,low_confidence_or_edge,1,47,v2_triple_barrier_meta,v2_risk_confidence_weighted
4,regime_M1,M1_low_rates,neutral,-0.755217,-0.9157,0.500000,-0.007552,low_confidence_or_edge,1,25,v2_triple_barrier_meta,v2_risk_confidence_weighted
5,regime_M1,other,CL_PANEL,0.314445,0.4957,0.500000,0.003144,score_selected,0,24,v2_triple_barrier_meta,v2_risk_confidence_weighted
6,regime_C1,C1_macro_tight_calm,neutral,-0.245205,0.0385,0.280634,-0.001734,low_confidence_or_edge,1,41,v2_triple_barrier_meta,v2_risk_confidence_weighted
7,regime_C1,C1_macro_loose,neutral,-0.755217,-0.9157,0.500000,-0.007552,low_confidence_or_edge,1,25,v2_triple_barrier_meta,v2_risk_confidence_weighted
8,regime_C1,other,CL_PANEL,0.314445,0.4957,0.500000,0.003144,score_selected,0,24,v2_triple_barrier_meta,v2_risk_confidence_weighted
9,ms_state_persist,MS_low,neutral,2.483535,0.5671,0.259802,-0.000908,low_confidence_or_edge,1,51,v2_triple_barrier_meta,v2_risk_confidence_weighted
10,ms_state_persist,MS_high,neutral,-0.517710,-0.5410,0.265743,-0.002070,low_confidence_or_edge,1,44,v2_triple_barrier_meta,v2_risk_confidence_weighted

## Unified Inference (bootstrap + paired test)

,comparison,mean_return_diff,mean_diff_ci_low,mean_diff_ci_high,sharpe_diff,sharpe_diff_ci_low,sharpe_diff_ci_high,paired_t_stat,paired_t_pvalue,n_obs,cost_bps,family,regime_id,regime_cell,model_id
0,strategy_vs_naive_50_50,-0.000074,-0.000215,0.000062,-0.022633,-0.095669,0.058862,-1.024579,0.308164,96,5.0,classical,NaN,NaN,NaN
1,ml_strategy_vs_passive,0.001624,-0.001342,0.004706,0.956836,-0.912522,3.000375,1.055266,0.298745,35,5.0,ml,NaN,NaN,NaN
2,CL_PANEL_vs_PASSIVE_SPREAD,0.000918,-0.000241,0.002275,0.120407,-0.335717,0.732331,1.421749,0.160548,58,5.0,regime_router,regime_R1,R1_high_spread,CL_PANEL
3,CL_SPREAD_vs_PASSIVE_SPREAD,0.000918,-0.000241,0.002275,0.120407,-0.335717,0.732331,1.421749,0.160548,58,5.0,regime_router,regime_R1,R1_high_spread,CL_SPREAD
4,ML_ENS_vs_PASSIVE_SPREAD,0.001624,-0.001342,0.004706,0.956836,-0.912522,3.000375,1.055266,0.298745,35,5.0,regime_router,regime_R1,R1_high_spread,ML_ENS
5,ML_LOGIT_vs_PASSIVE_SPREAD,0.000088,-0.002540,0.002857,0.009454,-1.611393,1.678781,0.063925,0.949405,35,5.0,regime_router,regime_R1,R1_high_spread,ML_LOGIT
6,ML_RF_vs_PASSIVE_SPREAD,0.001068,-0.002271,0.004544,0.595097,-1.483247,2.700249,0.614015,0.543292,35,5.0,regime_router,regime_R1,R1_high_spread,ML_RF
7,CL_PANEL_vs_PASSIVE_SPREAD,0.000040,-0.001102,0.001223,0.451347,-0.484709,1.437507,0.066976,0.947180,24,5.0,regime_router,regime_R1,other,CL_PANEL
8,CL_SPREAD_vs_PASSIVE_SPREAD,0.000040,-0.001102,0.001223,0.451347,-0.484709,1.437507,0.066976,0.947180,24,5.0,regime_router,regime_R1,other,CL_SPREAD
9,CL_PANEL_vs_PASSIVE_SPREAD,0.001200,-0.000794,0.002882,1.788708,-1.299119,7.486550,1.205519,0.249488,14,5.0,regime_router,regime_R1,R1_low_spread,CL_PANEL
10,CL_SPREAD_vs_PASSIVE_SPREAD,0.001200,-0.000794,0.002882,1.788708,-1.299119,7.486550,1.205519,0.249488,14,5.0,regime_router,regime_R1,R1_low_spread,CL_SPREAD
11,CL_PANEL_vs_PASSIVE_SPREAD,0.001241,-0.000499,0.003315,0.527347,-0.197308,1.310517,1.307259,0.197622,47,5.0,regime_router,regime_M1,M1_high_rates,CL_PANEL
12,CL_SPREAD_vs_PASSIVE_SPREAD,0.001241,-0.000499,0.003315,0.527347,-0.197308,1.310517,1.307259,0.197622,47,5.0,regime_router,regime_M1,M1_high_rates,CL_SPREAD
13,ML_ENS_vs_PASSIVE_SPREAD,0.001624,-0.001342,0.004706,0.956836,-0.912522,3.000375,1.055266,0.298745,35,5.0,regime_router,regime_M1,M1_high_rates,ML_ENS
14,ML_LOGIT_vs_PASSIVE_SPREAD,0.000088,-0.002540,0.002857,0.009454,-1.611393,1.678781,0.063925,0.949405,35,5.0,regime_router,regime_M1,M1_high_rates,ML_LOGIT
15,ML_RF_vs_PASSIVE_SPREAD,0.001068,-0.002271,0.004544,0.595097,-1.483247,2.700249,0.614015,0.543292,35,5.0,regime_router,regime_M1,M1_high_rates,ML_RF
16,CL_PANEL_vs_PASSIVE_SPREAD,0.001015,-0.000369,0.002257,0.445971,-1.202952,2.774274,1.519485,0.141706,25,5.0,regime_router,regime_M1,M1_low_rates,CL_PANEL
17,CL_SPREAD_vs_PASSIVE_SPREAD,0.001015,-0.000369,0.002257,0.445971,-1.202952,2.774274,1.519485,0.141706,25,5.0,regime_router,regime_M1,M1_low_rates,CL_SPREAD
18,CL_PANEL_vs_PASSIVE_SPREAD,0.000040,-0.001102,0.001223,0.451347,-0.484709,1.437507,0.066976,0.947180,24,5.0,regime_router,regime_M1,other,CL_PANEL
19,CL_SPREAD_vs_PASSIVE_SPREAD,0.000040,-0.001102,0.001223,0.451347,-0.484709,1.437507,0.066976,0.947180,24,5.0,regime_router,regime_M1,other,CL_SPREAD
20,CL_PANEL_vs_PASSIVE_SPREAD,0.000840,-0.000700,0.002297,0.166395,-0.588660,1.011924,1.073820,0.289339,41,5.0,regime_router,regime_C1,C1_macro_tight_calm,CL_PANEL
21,CL_SPREAD_vs_PASSIVE_SPREAD,0.000840,-0.000700,0.002297,0.166395,-0.588660,1.011924,1.073820,0.289339,41,5.0,regime_router,regime_C1,C1_macro_tight_calm,CL_SPREAD
22,ML_ENS_vs_PASSIVE_SPREAD,0.001804,-0.001245,0.005148,1.019812,-0.862578,3.250965,1.066132,0.294869,31,5.0,regime_router,regime_C1,C1_macro_tight_calm,ML_ENS
23,ML_LOGIT_vs_PASSIVE_SPREAD,0.000456,-0.002441,0.003406,0.164385,-1.557046,2.141895,0.299432,0.766675,31,5.0,regime_router,regime_C1,C1_macro_tight_calm,ML_LOGIT
24,ML_RF_vs_PASSIVE_SPREAD,0.000977,-0.002238,0.004170,0.500955,-1.491617,2.639615,0.568087,0.574203,31,5.0,regime_router,regime_C1,C1_macro_tight_calm,ML_RF
25,CL_PANEL_vs_PASSIVE_SPREAD,0.001015,-0.000369,0.002257,0.445971,-1.202952,2.774274,1.519485,0.141706,25,5.0,regime_router,regime_C1,C1_macro_loose,CL_PANEL
26,CL_SPREAD_vs_PASSIVE_SPREAD,0.001015,-0.000369,0.002257,0.445971,-1.202952,2.774274,1.519485,0.141706,25,5.0,regime_router,regime_C1,C1_macro_loose,CL_SPREAD
27,CL_PANEL_vs_PASSIVE_SPREAD,0.000040,-0.001102,0.001223,0.451347,-0.484709,1.437507,0.066976,0.947180,24,5.0,regime_router,regime_C1,other,CL_PANEL
28,CL_SPREAD_vs_PASSIVE_SPREAD,0.000040,-0.001102,0.001223,0.451347,-0.484709,1.437507,0.066976,0.947180,24,5.0,regime_router,regime_C1,other,CL_SPREAD
29,CL_PANEL_vs_PASSIVE_SPREAD,0.001646,0.000664,0.002667,0.739345,0.096502,2.217796,3.011541,0.004069,51,5.0,regime_router,ms_state_persist,MS_low,CL_PANEL
30,CL_SPREAD_vs_PASSIVE_SPREAD,0.001646,0.000664,0.002667,0.739345,0.096502,2.217796,3.011541,0.004069,51,5.0,regime_router,ms_state_persist,MS_low,CL_SPREAD
31,ML_ENS_vs_PASSIVE_SPREAD,0.001802,-0.000759,0.004394,1.778384,-2.760878,5.830404,1.267462,0.231164,12,5.0,regime_router,ms_state_persist,MS_low,ML_ENS
32,ML_LOGIT_vs_PASSIVE_SPREAD,0.002409,0.000587,0.004509,1.962613,0.538841,5.287347,2.329180,0.039927,12,5.0,regime_router,ms_state_persist,MS_low,ML_LOGIT
33,ML_RF_vs_PASSIVE_SPREAD,0.001031,-0.003213,0.004926,0.808849,-2.139299,7.678805,0.475710,0.643588,12,5.0,regime_router,ms_state_persist,MS_low,ML_RF
34,CL_PANEL_vs_PASSIVE_SPREAD,-0.000611,-0.002271,0.000990,-0.658556,-1.610310,0.188439,-0.728955,0.469981,44,5.0,regime_router,ms_state_persist,MS_high,CL_PANEL
35,CL_SPREAD_vs_PASSIVE_SPREAD,-0.000611,-0.002271,0.000990,-0.658556,-1.610310,0.188439,-0.728955,0.469981,44,5.0,regime_router,ms_state_persist,MS_high,CL_SPREAD
36,ML_ENS_vs_PASSIVE_SPREAD,0.000512,-0.003730,0.004929,0.192061,-2.147472,2.802941,0.232753,0.818105,23,5.0,regime_router,ms_state_persist,MS_high,ML_ENS
37,ML_LOGIT_vs_PASSIVE_SPREAD,-0.001416,-0.004990,0.002628,-0.872177,-3.392882,1.624612,-0.699640,0.491484,23,5.0,regime_router,ms_state_persist,MS_high,ML_LOGIT
38,ML_RF_vs_PASSIVE_SPREAD,-0.000013,-0.004332,0.004361,-0.086356,-2.796890,2.433180,-0.005750,0.995464,23,5.0,regime_router,ms_state_persist,MS_high,ML_RF

## Latest Signal Snapshot Used by Strategy Layer

,timestamp,signal_type,maturity_bucket,direction,strength,confidence
0,2026-05-23T18:13:43Z,spread,3M,0,1.4400,0.4800
1,2026-05-23T18:13:43Z,cip,3M,0,0.9400,0.3133
2,2026-05-23T18:13:43Z,spread,6M,0,1.3500,0.4500
3,2026-05-23T18:13:43Z,cip,6M,0,0.9900,0.3300
4,2026-05-23T18:13:43Z,spread,1Y,0,1.1400,0.3800
5,2026-05-23T18:13:43Z,cip,1Y,0,1.0600,0.3533
6,2026-05-23T18:13:43Z,spread,2Y,0,0.7900,0.2633
7,2026-05-23T18:13:43Z,cip,2Y,0,1.1400,0.3800
8,2026-05-23T18:13:43Z,spread,3Y,0,0.5400,0.1800
9,2026-05-23T18:13:43Z,cip,3Y,0,1.1800,0.3933
10,2026-05-23T18:13:43Z,spread,5Y,0,0.3300,0.1100
11,2026-05-23T18:13:43Z,cip,5Y,0,1.2100,0.4033
12,2026-05-23T18:13:43Z,spread,7Y,0,0.2000,0.0667
13,2026-05-23T18:13:43Z,cip,7Y,0,1.2300,0.4100
14,2026-05-23T18:13:43Z,spread,10Y,0,0.2000,0.0667
15,2026-05-23T18:13:43Z,cip,10Y,0,1.2300,0.4100
16,2026-05-23T18:13:43Z,spread,15Y,0,0.4800,0.1600
17,2026-05-23T18:13:43Z,cip,15Y,0,1.2200,0.4067
18,2026-05-23T18:13:43Z,spread,20Y,0,0.7100,0.2367
19,2026-05-23T18:13:43Z,cip,20Y,0,1.2200,0.4067
20,2026-05-23T18:13:43Z,spread,30Y,0,0.9900,0.3300
21,2026-05-23T18:13:43Z,cip,30Y,0,1.2200,0.4067
22,2026-05-23T18:13:43Z,factor,RU,0,0.1517,0.0506
23,2026-05-23T18:13:43Z,factor,CN,0,0.4993,0.1664

## What Is Statistically Supported vs Not Supported

- **Supported by statistical evidence**: risk-control behavior (turnover/cost discipline) and reproducible pipeline outputs.
- **Economically promising but not statistically strong**: return and Sharpe uplifts when confidence intervals overlap zero.
- **Not supported in this sample**: strong claims of persistent alpha across all regimes and costs.

Use this section with unified inference before drawing practical conclusions.

In [9]:
# Compare unified strategies on key practical metrics
metric_cols = ['ann_sharpe', 'ann_return', 'max_drawdown', 'var95_empirical', 'total_return', 'cagr']
show = unified[['strategy'] + [c for c in metric_cols if c in unified.columns]].copy() if not unified.empty and 'strategy' in unified.columns else pd.DataFrame()
display(Markdown('## Unified Strategy Comparison (Key Metrics)'))
display(show)

if not show.empty:
    cols = [c for c in metric_cols if c in show.columns]
    n = len(cols)
    rows = 2
    cols_n = int(np.ceil(n / rows)) if n > 0 else 1
    fig, axes = plt.subplots(rows, cols_n, figsize=(6 * cols_n, 8))
    axes = np.array(axes).reshape(-1)
    for i, col in enumerate(cols):
        show.plot(x='strategy', y=col, kind='bar', ax=axes[i], rot=30, legend=False, title=col)
    for j in range(len(cols), len(axes)):
        axes[j].axis('off')
    plt.tight_layout()
    plt.show()

if not unified_inf.empty:
    display(Markdown('## Statistical Significance (Strategy vs Benchmark)'))
    display(unified_inf)

## Unified Strategy Comparison (Key Metrics)

,strategy,ann_sharpe,ann_return,max_drawdown,var95_empirical,total_return,cagr
0,strategy,-0.3133,-0.004029,-0.0605,0.0061,-0.032362,-0.004104
1,naive_50_50,-0.2907,-0.003146,-0.0521,0.0053,-0.025309,-0.003199
2,disconnected_60_40,-0.3354,-0.004292,-0.0633,0.0063,-0.034385,-0.004364
3,ml_strategy,0.1463,0.002514,-0.0353,0.0093,0.006938,0.002373
4,ml_passive_spread,-0.8105,-0.016973,-0.0674,0.0114,-0.048925,-0.017051
5,CL_PANEL,-0.5386,-0.005523,-0.0311,0.0051,-0.026590,-0.005560
6,CL_SPREAD,-0.5386,-0.005523,-0.0311,0.0051,-0.026590,-0.005560
7,ML_ENS,0.1463,0.002514,-0.0353,0.0093,0.006938,0.002373
8,ML_LOGIT,-0.8011,-0.015913,-0.0593,0.0113,-0.045917,-0.015987
9,ML_RF,-0.2154,-0.004160,-0.0503,0.0093,-0.012585,-0.004333
10,CL_PANEL,0.4957,0.000991,-0.0018,0.0003,0.001979,0.000989
11,CL_SPREAD,0.4957,0.000991,-0.0018,0.0003,0.001979,0.000989
12,CL_PANEL,0.6327,0.002179,-0.0025,0.0011,0.002539,0.002176
13,CL_SPREAD,0.6327,0.002179,-0.0025,0.0011,0.002539,0.002176
14,CL_PANEL,-0.0276,-0.000234,-0.0238,0.0041,-0.001056,-0.000270
15,CL_SPREAD,-0.0276,-0.000234,-0.0238,0.0041,-0.001056,-0.000270
16,ML_ENS,0.1463,0.002514,-0.0353,0.0093,0.006938,0.002373
17,ML_LOGIT,-0.8011,-0.015913,-0.0593,0.0113,-0.045917,-0.015987
18,ML_RF,-0.2154,-0.004160,-0.0503,0.0093,-0.012585,-0.004333
19,CL_PANEL,-0.9157,-0.004602,-0.0123,0.0030,-0.009568,-0.004604
20,CL_SPREAD,-0.9157,-0.004602,-0.0123,0.0030,-0.009568,-0.004604
21,CL_PANEL,0.4957,0.000991,-0.0018,0.0003,0.001979,0.000989
22,CL_SPREAD,0.4957,0.000991,-0.0018,0.0003,0.001979,0.000989
23,CL_PANEL,-0.4443,-0.003570,-0.0252,0.0042,-0.012232,-0.003596
24,CL_SPREAD,-0.4443,-0.003570,-0.0252,0.0042,-0.012232,-0.003596
25,ML_ENS,0.0385,0.000694,-0.0353,0.0101,0.001387,0.000537
26,ML_LOGIT,-0.8169,-0.015486,-0.0521,0.0110,-0.039673,-0.015548
27,ML_RF,-0.4804,-0.009232,-0.0625,0.0115,-0.024028,-0.009371
28,CL_PANEL,-0.9157,-0.004602,-0.0123,0.0030,-0.009568,-0.004604
29,CL_SPREAD,-0.9157,-0.004602,-0.0123,0.0030,-0.009568,-0.004604
30,CL_PANEL,0.4957,0.000991,-0.0018,0.0003,0.001979,0.000989
31,CL_SPREAD,0.4957,0.000991,-0.0018,0.0003,0.001979,0.000989
32,CL_PANEL,-0.5485,-0.004344,-0.0277,0.0028,-0.018424,-0.004366
33,CL_SPREAD,-0.5485,-0.004344,-0.0277,0.0028,-0.018424,-0.004366
34,ML_ENS,0.5671,0.002111,-0.0009,0.0005,0.002107,0.002107
35,ML_LOGIT,0.7513,0.009399,-0.0099,0.0049,0.009367,0.009367
36,ML_RF,-0.4024,-0.007135,-0.0248,0.0092,-0.007255,-0.007255
37,CL_PANEL,-0.5410,-0.004684,-0.0272,0.0060,-0.017164,-0.004710
38,CL_SPREAD,-0.5410,-0.004684,-0.0272,0.0060,-0.017164,-0.004710
39,ML_ENS,-0.4875,-0.009763,-0.0428,0.0116,-0.018907,-0.009910
40,ML_LOGIT,-1.5517,-0.032900,-0.0626,0.0119,-0.061581,-0.032617
41,ML_RF,-0.7659,-0.016071,-0.0517,0.0116,-0.030745,-0.016160

NameError: name 'np' is not defined

## Interpretation prompts

- Does the strategy improve Sharpe vs naive and disconnected baselines?
- Are drawdown and empirical VaR acceptable for your target constraints?
- If differences are small, does signal confidence/weight mapping need recalibration?

In [10]:
# Major results summary (portfolio + risk)
from pathlib import Path
import pandas as pd
import numpy as np
from IPython.display import display, Markdown

ROOT = Path.cwd().resolve().parent if Path.cwd().name == 'notebooks' else Path.cwd().resolve()
PROCESSED = ROOT / 'data' / 'processed'

classical_path = PROCESSED / 'portfolio_backtest_summary.csv'
ml_path = PROCESSED / 'ml_backtest_summary.csv'

if not classical_path.exists():
    display(Markdown('**Major-results summary unavailable:** missing `portfolio_backtest_summary.csv`.'))
else:
    classical = pd.read_csv(classical_path)
    ml = pd.read_csv(ml_path) if ml_path.exists() else pd.DataFrame()

    # Keep major reported rows
    keep_classical = classical[classical['strategy'].isin(['strategy', 'naive_50_50', 'disconnected_60_40'])].copy()
    keep_classical['family'] = 'Classical allocation layer'

    major = [keep_classical]
    if not ml.empty:
        keep_ml = ml[ml['strategy'].isin(['ml_strategy', 'ml_passive_spread'])].copy()
        keep_ml['family'] = 'ML directional layer'
        major.append(keep_ml)

    major_df = pd.concat(major, ignore_index=True)
    metric_cols = [c for c in ['family', 'strategy', 'ann_sharpe', 'max_drawdown', 'var95_empirical', 'mean_return', 'hit_ratio', 'active_pct'] if c in major_df.columns]

    display(Markdown('## Major Results — Portfolio and Risk'))
    display(major_df[metric_cols].round(4))

    if 'strategy' in classical.columns:
        s = classical[classical['strategy'] == 'strategy']
        n = classical[classical['strategy'] == 'naive_50_50']
        if not s.empty and not n.empty:
            delta = pd.DataFrame([
                {
                    'Delta strategy_minus_naive': 'classical',
                    'ann_sharpe_delta': float(s['ann_sharpe'].iloc[0] - n['ann_sharpe'].iloc[0]),
                    'max_drawdown_delta': float(s['max_drawdown'].iloc[0] - n['max_drawdown'].iloc[0]),
                    'var95_empirical_delta': float(s['var95_empirical'].iloc[0] - n['var95_empirical'].iloc[0]),
                    'mean_return_delta': float(s['mean_return'].iloc[0] - n['mean_return'].iloc[0]),
                }
            ])
            display(Markdown('### Strategy uplift vs naive baseline'))
            display(delta.round(6))

## Major Results — Portfolio and Risk

,family,strategy,ann_sharpe,max_drawdown,var95_empirical,mean_return,hit_ratio,active_pct
0,Classical allocation layer,strategy,-0.3133,-0.0605,0.0061,-0.0003,0.4583,0.7083
1,Classical allocation layer,naive_50_50,-0.2907,-0.0521,0.0053,-0.0003,0.4479,1.0000
2,Classical allocation layer,disconnected_60_40,-0.3354,-0.0633,0.0063,-0.0004,0.4375,1.0000
3,ML directional layer,ml_strategy,0.1463,-0.0353,0.0093,0.0002,0.2857,0.5143
4,ML directional layer,ml_passive_spread,-0.8105,-0.0674,0.0114,-0.0014,0.3429,1.0000

### Strategy uplift vs naive baseline

,Delta strategy_minus_naive,ann_sharpe_delta,max_drawdown_delta,var95_empirical_delta,mean_return_delta
0,classical,-0.0226,-0.0084,0.0008,-0.000074